export const INITIAL_STATE = {
  checkingState: true,
  enabling: false,
  disabling: false,
  discovering: false,
  scanning: false,
  isEnabled: false,
  ready: false,
  connecting: false,
  pairing: false,
  connected: false,
  devices: [],
  unpairedDevices: [],
  active: null,
  writing: false,
  isAvailable: false,
  error: {},
  data: '',
}
